os: Visual Studio 2015

cache:
  - 'C:\Users\appveyor\.cargo'
  - target

matrix:
  allow_failures:
    - channel: nightly

install:
#- appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
#- rustup-init.exe -y --default-host %target% --default-toolchain %channel%
#- set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
#- rustc -V
#- cargo -V
#
- cmake --version
#
- choco install ninja
- ninja --version
#
- set PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build";%PATH%
- vcvarsall x64
- cl

environment:
  RUST_BACKTRACE: 1

build_script:
- cmd: cd tests && cd test-cmake && cmake . -G Ninja -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_C_COMPILER=cl.exe && cmake --build .
- cmd: cargo build %RELEASE%

test_script:
- cmd: cargo test --all %RELEASE% --verbose

for:

-
  branches:
    only:
      - ci-cmake-ninja-vs2017
  environment:
    matrix:
      - channel: stable
        target: x86_64-pc-windows-msvc
        RELEASE: --release

-
  branches:
    only:
      - master
  environment:
    matrix:
      - channel: stable
        target: x86_64-pc-windows-msvc
      - channel: beta
        target: x86_64-pc-windows-msvc
      - channel: nightly
        target: x86_64-pc-windows-msvc
      - channel: 1.22.0 # Oldest supported version. Keep in sync with README.md.
        target: x86_64-pc-windows-msvc
        # Build a release build on master to make sure it builds.
      - channel: stable
        target: x86_64-pc-windows-msvc
        RELEASE: --release

-
  branches:
    only:
      - /\d+\.\d+\.\d+/
  environment:
    # Only build a release build for releases.
    channel: stable
    target: x86_64-pc-windows-msvc
    RELEASE: --release

  before_deploy:
    - ps: |
          $NAME = "sccache-${env:APPVEYOR_REPO_TAG_NAME}-${env:TARGET}"
          New-Item -Path $NAME -ItemType directory
          Copy-Item target/release/sccache.exe "${NAME}/"
          Copy-Item LICENSE "${NAME}/"
          Copy-Item README.md "${NAME}/"
          7z a -ttar "${NAME}.tar" "${NAME}"
          7z a "${NAME}.tar.gz" "${NAME}.tar"
          Push-AppveyorArtifact "${NAME}.tar.gz"

  deploy:
    artifact: /.*\.tar.gz/
    auth_token:
      secure: NKcPr8KYJE2osDxfO1xBDQHQRgJrhgItv2op6KKZSfLB01rq08M3243XdN3J5aaJ
    description: ''
    on:
      appveyor_repo_tag: true
    provider: GitHub
    force_update: true
